spring.application.name=Theocash

spring.datasource.url=jdbc:mysql://127.0.0.1:3307/Theocash?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Got#9900
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update